default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ultimate_choice_development
  host: db
  username: postgres
  password: password

test:
  <<: *default
  database: ultimate_choice_test
  host: db
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
  