 default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ultimate_choice_development

test:
  <<: *default
  database: ultimate_choice_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: ultimate_choice_production
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
